# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.multicast_group_service_api import MulticastGroupServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMulticastGroupServiceApi(unittest.TestCase):
    """MulticastGroupServiceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.multicast_group_service_api.MulticastGroupServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_device(self):
        """Test case for add_device

        AddDevice adds the given device to the multicast-group.  # noqa: E501
        """
        pass

    def test_create(self):
        """Test case for create

        Create creates the given multicast-group.  # noqa: E501
        """
        pass

    def test_delete(self):
        """Test case for delete

        Delete deletes a multicast-group given an ID.  # noqa: E501
        """
        pass

    def test_enqueue(self):
        """Test case for enqueue

        Enqueue adds the given item to the multicast-queue.  # noqa: E501
        """
        pass

    def test_flush_queue(self):
        """Test case for flush_queue

        FlushQueue flushes the multicast-group queue.  # noqa: E501
        """
        pass

    def test_get(self):
        """Test case for get

        Get returns a multicast-group given an ID.  # noqa: E501
        """
        pass

    def test_list(self):
        """Test case for list

        List lists the available multicast-groups.  # noqa: E501
        """
        pass

    def test_list_queue(self):
        """Test case for list_queue

        ListQueue lists the items in the multicast-group queue.  # noqa: E501
        """
        pass

    def test_remove_device(self):
        """Test case for remove_device

        RemoveDevice removes the given device from the multicast-group.  # noqa: E501
        """
        pass

    def test_update(self):
        """Test case for update

        Update updates the given multicast-group.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
