# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.api_get_http_integration_response import ApiGetHTTPIntegrationResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestApiGetHTTPIntegrationResponse(unittest.TestCase):
    """ApiGetHTTPIntegrationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiGetHTTPIntegrationResponse(self):
        """Test ApiGetHTTPIntegrationResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_get_http_integration_response.ApiGetHTTPIntegrationResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
