# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.device_queue_service_api import DeviceQueueServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDeviceQueueServiceApi(unittest.TestCase):
    """DeviceQueueServiceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.device_queue_service_api.DeviceQueueServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_enqueue(self):
        """Test case for enqueue

        Enqueue adds the given item to the device-queue.  # noqa: E501
        """
        pass

    def test_flush(self):
        """Test case for flush

        Flush flushes the downlink device-queue.  # noqa: E501
        """
        pass

    def test_list(self):
        """Test case for list

        List lists the items in the device-queue.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
