# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.application_service_api import ApplicationServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestApplicationServiceApi(unittest.TestCase):
    """ApplicationServiceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.application_service_api.ApplicationServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create(self):
        """Test case for create

        Create creates the given application.  # noqa: E501
        """
        pass

    def test_create_http_integration(self):
        """Test case for create_http_integration

        CreateHTTPIntegration creates a HTTP application-integration.  # noqa: E501
        """
        pass

    def test_create_influx_db_integration(self):
        """Test case for create_influx_db_integration

        CreateInfluxDBIntegration create an InfluxDB application-integration.  # noqa: E501
        """
        pass

    def test_create_things_board_integration(self):
        """Test case for create_things_board_integration

        CreateThingsBoardIntegration creates a ThingsBoard application-integration.  # noqa: E501
        """
        pass

    def test_delete(self):
        """Test case for delete

        Delete deletes the given application.  # noqa: E501
        """
        pass

    def test_delete_http_integration(self):
        """Test case for delete_http_integration

        DeleteIntegration deletes the HTTP application-integration.  # noqa: E501
        """
        pass

    def test_delete_influx_db_integration(self):
        """Test case for delete_influx_db_integration

        DeleteInfluxDBIntegration deletes the InfluxDB application-integration.  # noqa: E501
        """
        pass

    def test_delete_things_board_integration(self):
        """Test case for delete_things_board_integration

        DeleteThingsBoardIntegration deletes the ThingsBoard application-integration.  # noqa: E501
        """
        pass

    def test_get(self):
        """Test case for get

        Get returns the requested application.  # noqa: E501
        """
        pass

    def test_get_http_integration(self):
        """Test case for get_http_integration

        GetHTTPIntegration returns the HTTP application-integration.  # noqa: E501
        """
        pass

    def test_get_influx_db_integration(self):
        """Test case for get_influx_db_integration

        GetInfluxDBIntegration returns the InfluxDB application-integration.  # noqa: E501
        """
        pass

    def test_get_things_board_integration(self):
        """Test case for get_things_board_integration

        GetThingsBoardIntegration returns the ThingsBoard application-integration.  # noqa: E501
        """
        pass

    def test_list(self):
        """Test case for list

        List lists the available applications.  # noqa: E501
        """
        pass

    def test_list_integrations(self):
        """Test case for list_integrations

        ListIntegrations lists all configured integrations.  # noqa: E501
        """
        pass

    def test_update(self):
        """Test case for update

        Update updates the given application.  # noqa: E501
        """
        pass

    def test_update_http_integration(self):
        """Test case for update_http_integration

        UpdateHTTPIntegration updates the HTTP application-integration.  # noqa: E501
        """
        pass

    def test_update_influx_db_integration(self):
        """Test case for update_influx_db_integration

        UpdateInfluxDBIntegration updates the InfluxDB application-integration.  # noqa: E501
        """
        pass

    def test_update_things_board_integration(self):
        """Test case for update_things_board_integration

        UpdateThingsBoardIntegration updates the ThingsBoard application-integration.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
