# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.device_profile_service_api import DeviceProfileServiceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDeviceProfileServiceApi(unittest.TestCase):
    """DeviceProfileServiceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.device_profile_service_api.DeviceProfileServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create(self):
        """Test case for create

        Create creates the given device-profile.  # noqa: E501
        """
        pass

    def test_delete(self):
        """Test case for delete

        Delete deletes the device-profile matching the given id.  # noqa: E501
        """
        pass

    def test_get(self):
        """Test case for get

        Get returns the device-profile matching the given id.  # noqa: E501
        """
        pass

    def test_list(self):
        """Test case for list

        List lists the available device-profiles.  # noqa: E501
        """
        pass

    def test_update(self):
        """Test case for update

        Update updates the given device-profile.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
