# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.api_organization_user import ApiOrganizationUser  # noqa: F401,E501


class ApiAddOrganizationUserRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'organization_user': 'ApiOrganizationUser'
    }

    attribute_map = {
        'organization_user': 'organizationUser'
    }

    def __init__(self, organization_user=None):  # noqa: E501
        """ApiAddOrganizationUserRequest - a model defined in Swagger"""  # noqa: E501

        self._organization_user = None
        self.discriminator = None

        if organization_user is not None:
            self.organization_user = organization_user

    @property
    def organization_user(self):
        """Gets the organization_user of this ApiAddOrganizationUserRequest.  # noqa: E501

        Organization-user object to create.  # noqa: E501

        :return: The organization_user of this ApiAddOrganizationUserRequest.  # noqa: E501
        :rtype: ApiOrganizationUser
        """
        return self._organization_user

    @organization_user.setter
    def organization_user(self, organization_user):
        """Sets the organization_user of this ApiAddOrganizationUserRequest.

        Organization-user object to create.  # noqa: E501

        :param organization_user: The organization_user of this ApiAddOrganizationUserRequest.  # noqa: E501
        :type: ApiOrganizationUser
        """

        self._organization_user = organization_user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiAddOrganizationUserRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiAddOrganizationUserRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
