# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ApiEnqueueDeviceQueueItemResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'f_cnt': 'int'
    }

    attribute_map = {
        'f_cnt': 'fCnt'
    }

    def __init__(self, f_cnt=None):  # noqa: E501
        """ApiEnqueueDeviceQueueItemResponse - a model defined in Swagger"""  # noqa: E501

        self._f_cnt = None
        self.discriminator = None

        if f_cnt is not None:
            self.f_cnt = f_cnt

    @property
    def f_cnt(self):
        """Gets the f_cnt of this ApiEnqueueDeviceQueueItemResponse.  # noqa: E501

        Frame-counter for the enqueued payload.  # noqa: E501

        :return: The f_cnt of this ApiEnqueueDeviceQueueItemResponse.  # noqa: E501
        :rtype: int
        """
        return self._f_cnt

    @f_cnt.setter
    def f_cnt(self, f_cnt):
        """Sets the f_cnt of this ApiEnqueueDeviceQueueItemResponse.

        Frame-counter for the enqueued payload.  # noqa: E501

        :param f_cnt: The f_cnt of this ApiEnqueueDeviceQueueItemResponse.  # noqa: E501
        :type: int
        """

        self._f_cnt = f_cnt

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiEnqueueDeviceQueueItemResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiEnqueueDeviceQueueItemResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
