# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ApiGatewayBoard(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'fine_timestamp_key': 'str',
        'fpga_id': 'str'
    }

    attribute_map = {
        'fine_timestamp_key': 'fineTimestampKey',
        'fpga_id': 'fpgaID'
    }

    def __init__(self, fine_timestamp_key=None, fpga_id=None):  # noqa: E501
        """ApiGatewayBoard - a model defined in Swagger"""  # noqa: E501

        self._fine_timestamp_key = None
        self._fpga_id = None
        self.discriminator = None

        if fine_timestamp_key is not None:
            self.fine_timestamp_key = fine_timestamp_key
        if fpga_id is not None:
            self.fpga_id = fpga_id

    @property
    def fine_timestamp_key(self):
        """Gets the fine_timestamp_key of this ApiGatewayBoard.  # noqa: E501

        Fine-timestamp AES decryption key (HEX encoded) (optional).  # noqa: E501

        :return: The fine_timestamp_key of this ApiGatewayBoard.  # noqa: E501
        :rtype: str
        """
        return self._fine_timestamp_key

    @fine_timestamp_key.setter
    def fine_timestamp_key(self, fine_timestamp_key):
        """Sets the fine_timestamp_key of this ApiGatewayBoard.

        Fine-timestamp AES decryption key (HEX encoded) (optional).  # noqa: E501

        :param fine_timestamp_key: The fine_timestamp_key of this ApiGatewayBoard.  # noqa: E501
        :type: str
        """

        self._fine_timestamp_key = fine_timestamp_key

    @property
    def fpga_id(self):
        """Gets the fpga_id of this ApiGatewayBoard.  # noqa: E501

        FPGA ID of the gateway (HEX encoded) (optional).  # noqa: E501

        :return: The fpga_id of this ApiGatewayBoard.  # noqa: E501
        :rtype: str
        """
        return self._fpga_id

    @fpga_id.setter
    def fpga_id(self, fpga_id):
        """Sets the fpga_id of this ApiGatewayBoard.

        FPGA ID of the gateway (HEX encoded) (optional).  # noqa: E501

        :param fpga_id: The fpga_id of this ApiGatewayBoard.  # noqa: E501
        :type: str
        """

        self._fpga_id = fpga_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiGatewayBoard, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiGatewayBoard):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
