# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.api_fuota_deployment_device_state import ApiFUOTADeploymentDeviceState  # noqa: F401,E501


class ApiFUOTADeploymentDeviceListItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'created_at': 'datetime',
        'dev_eui': 'str',
        'device_name': 'str',
        'error_message': 'str',
        'state': 'ApiFUOTADeploymentDeviceState',
        'updated_at': 'datetime'
    }

    attribute_map = {
        'created_at': 'createdAt',
        'dev_eui': 'devEUI',
        'device_name': 'deviceName',
        'error_message': 'errorMessage',
        'state': 'state',
        'updated_at': 'updatedAt'
    }

    def __init__(self, created_at=None, dev_eui=None, device_name=None, error_message=None, state=None, updated_at=None):  # noqa: E501
        """ApiFUOTADeploymentDeviceListItem - a model defined in Swagger"""  # noqa: E501

        self._created_at = None
        self._dev_eui = None
        self._device_name = None
        self._error_message = None
        self._state = None
        self._updated_at = None
        self.discriminator = None

        if created_at is not None:
            self.created_at = created_at
        if dev_eui is not None:
            self.dev_eui = dev_eui
        if device_name is not None:
            self.device_name = device_name
        if error_message is not None:
            self.error_message = error_message
        if state is not None:
            self.state = state
        if updated_at is not None:
            self.updated_at = updated_at

    @property
    def created_at(self):
        """Gets the created_at of this ApiFUOTADeploymentDeviceListItem.  # noqa: E501

        Created at timestamp.  # noqa: E501

        :return: The created_at of this ApiFUOTADeploymentDeviceListItem.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ApiFUOTADeploymentDeviceListItem.

        Created at timestamp.  # noqa: E501

        :param created_at: The created_at of this ApiFUOTADeploymentDeviceListItem.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def dev_eui(self):
        """Gets the dev_eui of this ApiFUOTADeploymentDeviceListItem.  # noqa: E501

        Device EUI (HEX encoded).  # noqa: E501

        :return: The dev_eui of this ApiFUOTADeploymentDeviceListItem.  # noqa: E501
        :rtype: str
        """
        return self._dev_eui

    @dev_eui.setter
    def dev_eui(self, dev_eui):
        """Sets the dev_eui of this ApiFUOTADeploymentDeviceListItem.

        Device EUI (HEX encoded).  # noqa: E501

        :param dev_eui: The dev_eui of this ApiFUOTADeploymentDeviceListItem.  # noqa: E501
        :type: str
        """

        self._dev_eui = dev_eui

    @property
    def device_name(self):
        """Gets the device_name of this ApiFUOTADeploymentDeviceListItem.  # noqa: E501

        Device name.  # noqa: E501

        :return: The device_name of this ApiFUOTADeploymentDeviceListItem.  # noqa: E501
        :rtype: str
        """
        return self._device_name

    @device_name.setter
    def device_name(self, device_name):
        """Sets the device_name of this ApiFUOTADeploymentDeviceListItem.

        Device name.  # noqa: E501

        :param device_name: The device_name of this ApiFUOTADeploymentDeviceListItem.  # noqa: E501
        :type: str
        """

        self._device_name = device_name

    @property
    def error_message(self):
        """Gets the error_message of this ApiFUOTADeploymentDeviceListItem.  # noqa: E501

        Error message (in case of error state).  # noqa: E501

        :return: The error_message of this ApiFUOTADeploymentDeviceListItem.  # noqa: E501
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this ApiFUOTADeploymentDeviceListItem.

        Error message (in case of error state).  # noqa: E501

        :param error_message: The error_message of this ApiFUOTADeploymentDeviceListItem.  # noqa: E501
        :type: str
        """

        self._error_message = error_message

    @property
    def state(self):
        """Gets the state of this ApiFUOTADeploymentDeviceListItem.  # noqa: E501

        Device state.  # noqa: E501

        :return: The state of this ApiFUOTADeploymentDeviceListItem.  # noqa: E501
        :rtype: ApiFUOTADeploymentDeviceState
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this ApiFUOTADeploymentDeviceListItem.

        Device state.  # noqa: E501

        :param state: The state of this ApiFUOTADeploymentDeviceListItem.  # noqa: E501
        :type: ApiFUOTADeploymentDeviceState
        """

        self._state = state

    @property
    def updated_at(self):
        """Gets the updated_at of this ApiFUOTADeploymentDeviceListItem.  # noqa: E501

        Updated at timestamp.  # noqa: E501

        :return: The updated_at of this ApiFUOTADeploymentDeviceListItem.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this ApiFUOTADeploymentDeviceListItem.

        Updated at timestamp.  # noqa: E501

        :param updated_at: The updated_at of this ApiFUOTADeploymentDeviceListItem.  # noqa: E501
        :type: datetime
        """

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiFUOTADeploymentDeviceListItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiFUOTADeploymentDeviceListItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
