# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.api_application import ApiApplication  # noqa: F401,E501


class ApiCreateApplicationRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'application': 'ApiApplication'
    }

    attribute_map = {
        'application': 'application'
    }

    def __init__(self, application=None):  # noqa: E501
        """ApiCreateApplicationRequest - a model defined in Swagger"""  # noqa: E501

        self._application = None
        self.discriminator = None

        if application is not None:
            self.application = application

    @property
    def application(self):
        """Gets the application of this ApiCreateApplicationRequest.  # noqa: E501

        Application object to create.  # noqa: E501

        :return: The application of this ApiCreateApplicationRequest.  # noqa: E501
        :rtype: ApiApplication
        """
        return self._application

    @application.setter
    def application(self, application):
        """Sets the application of this ApiCreateApplicationRequest.

        Application object to create.  # noqa: E501

        :param application: The application of this ApiCreateApplicationRequest.  # noqa: E501
        :type: ApiApplication
        """

        self._application = application

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiCreateApplicationRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiCreateApplicationRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
