# coding: utf-8

"""
    LoRa App Server REST API

     For more information about the usage of the LoRa App Server (REST) API, see [https://docs.loraserver.io/lora-app-server/api/](https://docs.loraserver.io/lora-app-server/api/).   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.api_gateway_profile import ApiGatewayProfile  # noqa: F401,E501


class ApiCreateGatewayProfileRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'gateway_profile': 'ApiGatewayProfile'
    }

    attribute_map = {
        'gateway_profile': 'gatewayProfile'
    }

    def __init__(self, gateway_profile=None):  # noqa: E501
        """ApiCreateGatewayProfileRequest - a model defined in Swagger"""  # noqa: E501

        self._gateway_profile = None
        self.discriminator = None

        if gateway_profile is not None:
            self.gateway_profile = gateway_profile

    @property
    def gateway_profile(self):
        """Gets the gateway_profile of this ApiCreateGatewayProfileRequest.  # noqa: E501

        Gateway-profile object to create.  # noqa: E501

        :return: The gateway_profile of this ApiCreateGatewayProfileRequest.  # noqa: E501
        :rtype: ApiGatewayProfile
        """
        return self._gateway_profile

    @gateway_profile.setter
    def gateway_profile(self, gateway_profile):
        """Sets the gateway_profile of this ApiCreateGatewayProfileRequest.

        Gateway-profile object to create.  # noqa: E501

        :param gateway_profile: The gateway_profile of this ApiCreateGatewayProfileRequest.  # noqa: E501
        :type: ApiGatewayProfile
        """

        self._gateway_profile = gateway_profile

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiCreateGatewayProfileRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiCreateGatewayProfileRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
